name: deeplearning4d
description: Tensorflow Playground Neural Net implementation on Dart
version: 0.0.1
author: Marat Gubaidullin <marat.gubaidullin@gmail.com>
homepage: https://github.com/deeplearning4d/deeplearning4d

environment:
  sdk: 

dev_dependencies:
  test:
